- name: Create artifactory directory
  file:
    path: /var/opt/jfrog/artifactory
    state: directory
    mode: '0755'

- name: Add artifactory group
  group:
    name: artifactory
    state: present

- name: stat artifactory
  stat: path=/opt/jfrog/artifactory
  register: artifactory_stat

- name: Creates jfrog directory
  file:
    path: /opt/jfrog
    state: directory 

- name: Download artifactory
  get_url:
    url: https://bintray.com/jfrog/artifactory/download_file?file_path=jfrog-artifactory-oss-6.12.2.zip
    dest: /tmp/jfrog-artifactory-oss-6.12.2.zip
    mode: '0440'

- name: Install unzip
  apt:
    name: unzip  

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /tmp/jfrog-artifactory-oss-6.12.2.zip
    dest: /opt
    remote_src: yes

- name:
  shell: mv /opt/artifactory-oss-6.12.2 /opt/jfrog/artifactory
  when: artifactory_stat.stat.islnk is not defined

- name: Add artifactory user
  user:
    name: artifactory
    group: artifactory
    shell: /bin/false
    home: /opt/jfrog/artifactory

- name: Copy default settings
  copy:
    src: /vagrant/provision/artifactory.default
    dest: /opt/jfrog/artifactory/bin/artifactory.default
    owner: artifactory
    group: artifactory
    mode: '0644'

- name: Change owner
  file: 
    dest: /opt/jfrog
    owner: artifactory 
    group: artifactory
    recurse: yes

- name: Run artifactory installation script
  shell: /opt/jfrog/artifactory/bin/installService.sh

- name: restart service
  systemd:
    state: started
    name: artifactory
    no_block: yes

- name: Wait for port 8081 to become open on the host
  wait_for:
    port: 8081
    delay: 30