- name: Add google download key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add google download repo
  apt_repository:
    repo: deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Chrome
  apt:
    name: openjdk-8-jdk
    state: google-chrome-stable