- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - 'git'
    - 'apt-transport-https'
    - 'wget'
    - 'gnupg2'

- name: Add docker key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: "docker-ce"
    state: latest

- name: Give insecure permissions to an existing file
  file:
    path: /var/run/docker.sock
    state: touch
    mode: u=rw,g=rw,o=rw

- name: Install Python-PIP
  apt:
    name: "python-pip"
    state: latest

- name: Install docker-py
  raw: "pip install {{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - 'docker-py'

- name: Create a network
  docker_network:
    name: dockernet
    driver: bridge
    ipam_config:
    - subnet: 192.168.0.0/24
      gateway: 192.168.0.1