- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - 'openssh-server'
    - 'postfix'
    - 'openssl'
    - 'tzdata'
    - 'gnupg2'

- name: Download GitLab preparation script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh

- name: Run preparation script
  script: /tmp/script.deb.sh

- name: Install GitLab
  apt:
    name: gitlab-ce
    state: latest

- name: Change default URL
  replace:
    path: /etc/gitlab/gitlab.rb
    regexp: 'external_url\shttp:\/\/gitlab\.example\.com'
    replace: 'external_url http://dev.gitlab'

- name: Reconfigure GitLab (first run).
  command: gitlab-ctl reconfigure  